### ISSUE TITLE
if any one intrested in only the backend part of this project

### ISSUE THREAD

**Issue by bibektimilsina00** [fastapi/full-stack-fastapi-template#1325]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

https://github.com/bibektimilsina00/FastAPI-PgStarterKit

**Comment by FlaccidFacade** [comment]
this is great! can I assist with making  an oracle -dB template?

**Comment by bibektimilsina00** [comment]
yes ofcourse you can

**Comment by FlaccidFacade** [comment]
why use sql alchemy over fast api's model db?

**Comment by bibektimilsina00** [comment]
it reduce the boilerplate code cause you can only define the models once not needed to define sql model and pydentic model seperately

**Comment by FlaccidFacade** [comment]
>It combines SQLAlchemy and Pydantic and tries to simplify the code you write as much as possible, allowing you to reduce the >code duplication to a minimum, but while getting the best developer experience possible.
>
>SQLModel is, in fact, a thin layer on top of Pydantic and SQLAlchemy, carefully designed to be compatible with both.

 [SQLModel Docs in fastapi usage](https://sqlmodel.tiangolo.com/#sql-databases-in-fastapi)
 I am still learning this but it seems to boast a solution for what you're claiming.

**Comment by tiangolo** [comment]
Hey @bibektimilsina00, the checkbox that says you're @tiangolo is to prevent things that are not issues here in the issues. It would be better to post it as blog post or similar. Thanks for the interest! I'll now close this one. :coffee:

**Comment by TaichiLi** [comment]
Hello, do you have a template for Oracle databases?@FlaccidFacade

**Comment by FlaccidFacade** [comment]
No template but I did end up using sqlalchemy, too. Their docs make it fairly easy to leverage but there are a few gotchas depending on your version of oracle DB. so read carefully or email me (found on profile) if you have any specific questions. I'd be happy to help make an open source example.
