### ISSUE TITLE
The code is very bad. Fastapi provides dependency injection function, but developers don’t know how to use it.

### ISSUE THREAD

**Issue by jianchao123** [fastapi/full-stack-fastapi-template#1334]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

The code is very bad. Fastapi provides dependency injection function, but developers don’t know how to use it.I suspect the developer has no real project experience

**Comment by jianchao123** [comment]
The directory structure of the project is not designed hierarchically. I would like to ask developers what is MVC?

**Comment by jianchao123** [comment]
The app/main.py file is at the top level of the directory structure, but it imports the api_router object from a lower-level file. This shouldn't be a mistake made by a developer.

**Comment by jianchao123** [comment]
一坨大便

**Comment by Atticuszz** [comment]
shut up,you are the shame  of chinese  developer.

**Comment by jianchao123** [comment]
> shut up,you are the shame of chinese developer.
> 
> useless issues should be closed.

菜鸡，看看你写的破烂代码。async def identify_ws(connection: WebSocketConnection):
    while True:
        # test identifyResult
        try:
            rec_data = await connection.receive_data(Face2SearchSchema)
            logger.debug("rec_data:", rec_data)
            search_data = Face2Search.from_schema(rec_data)
            logger.debug(f"get the search data:{search_data}")

            await task_queue.put_async((TaskType.IDENTIFY, search_data.to_face()))

            try:
                res: MatchedResult = await result_queue.get_async()
                result = IdentifyResult.from_matched_result(res)
                await connection.send_data(result)
            except Empty:
                logger.warn("empty in result queue")

            # time_now = datetime.datetime.now()
            # result = IdentifyResult(
            #     uid=str(uuid.uuid4()),
            #     name=session.user.user_metadata.get("name"),
            #     time=time_now.strftime("%Y-%m-%d %H:%M:%S"),
            #     uid=search_data.uid,
            #     score=0.99
            # )

            # await asyncio.sleep(1)  # 示例延时
        except (
            ConnectionClosedOK,
            ConnectionClosedError,
            RuntimeError,
            WebSocketDisconnect,
        ) as e:
            logger.info(f"WebSocket error occurred: {e.__class__.__name__} - {e}")
            logger.info(f"Client left the chat")
            break

**Comment by jianchao123** [comment]
> shut up,you are the shame of chinese developer.
> 
> useless issues should be closed.

建议你注销github账号，不要再给中国开发者丢脸

**Comment by Atticuszz** [comment]
@alejsdev I respectfully request that this issue be closed. The content appears to contain unsubstantiated claims and potentially harmful remakes that does not align with our community guidelines.
