### ISSUE TITLE
get_current_active_superuser() does not seem to check that superuser is actually active

### ISSUE THREAD

**Issue by nsxsnx** [fastapi/full-stack-fastapi-template#537]
Hello,
Please, correct me if I'm wrong, but I believe here in **/backend/app/app/api/deps.py**:
```
def get_current_active_superuser(
    current_user: models.User = Depends(get_current_user),
) -> models.User:
```
we must depend on **get_current_active_user**, not **get_current_user** to make sure that superuser is active.

**Comment by nsxsnx** [comment]
Created pull request #538 to fix

**Comment by danieldiamond** [comment]
@nsxsnx, were you happy with the updates? Can you close this issue now?

**Comment by nsxsnx** [comment]
Thank you
